language: ruby
bundler_args: --without debug
rvm:
  - 1.9.3
  #- jruby-19mode  
  #- 2.0
  #- 2.1
#matrix:
#  include:
#    - rvm: jruby
#      env: JRUBY_OPTS="--2.0"
before_script:
  - mysql -e 'create database dummy_test;'
  - cd test/dummy && RAILS_ENV=test bundle exec rake --trace db:schema:load db:migrate && cd ../../